import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { Toaster } from 'react-hot-toast';
import App from './App.jsx';
import { AuthProvider } from './context/AuthContext.jsx';
import { PlayerProvider } from './context/PlayerContext.jsx';
import ErrorBoundary from './components/ErrorBoundary.jsx';
import './index.css';
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><ErrorBoundary><BrowserRouter><AuthProvider><PlayerProvider><App/><Toaster position="top-right" toastOptions={{style:{background:'#111827',color:'#fff',border:'1px solid rgba(255,255,255,.12)'}}}/></PlayerProvider></AuthProvider></BrowserRouter></ErrorBoundary></React.StrictMode>);
