import express from 'express';
import cors from 'cors';
import authRoutes from './routes/authRoutes.js';
import songRoutes from './routes/songRoutes.js';
import playlistRoutes from './routes/playlistRoutes.js';
import favoriteRoutes from './routes/favoriteRoutes.js';
import userRoutes from './routes/userRoutes.js';
const app = express();
app.use(cors({ origin: true, credentials: true }));
app.use(express.json({ limit: '10mb' }));
app.get('/api/health', (req, res) => res.json({ ok: true, app: 'Tune Fox' }));
app.use('/api/auth', authRoutes); app.use('/api/songs', songRoutes); app.use('/api/playlists', playlistRoutes); app.use('/api/favorites', favoriteRoutes); app.use('/api/users', userRoutes);
app.use((req, res) => res.status(404).json({ message: 'Route not found' }));
app.use((err, req, res, next) => res.status(err.status || 500).json({ message: err.message || 'Server error' }));
export default app;
